version: '3.9'

services:
    django:
        build: ./backend
        container_name: api-container
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        env_file:
            - ./backend/.env
        volumes:
            - ./backend/:/srv/app
            - static:/srv/app/static
            - media:/srv/app/media
            
    nginx:
        build: ./nginx
        container_name: dev-nginx
        ports:
            - "80:80"
        restart: always
        volumes:
            - static:/srv/app/static
            - media:/srv/app/media
      
volumes:
  media:
  static: